### ISSUE TITLE
TypeError on NodeJS v9.2.0

### ISSUE THREAD

**Issue by EricLanduyt** [davidchambers/nucleotides#6]
When I require('nucleotides') on NodeJS 9.2, it fails with this error:
```
/home/node/node_modules/nucleotides/nucleotides.js:36
    return ctor.prototype[name];
                         ^

TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at /home/node/node_modules/nucleotides/nucleotides.js:36:26
    at /home/node/node_modules/nucleotides/node_modules/ramda/ramda.js:184:35
    ..
```

**Comment by davidchambers** [comment]
Thank you for reporting this, @EricLanduyt. I'll submit a fix shortly. :)
